### ISSUE TITLE
NTR: Request for S04 model prediction of fluorescence

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S04#11]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>model prediction of fluorescence <p><b>Definition</b><p> The value was obtained using a numerical model to simulate fluorescence, which is calculated by simulating the absorption of a substance (pigment, protein) in a cell followed by release in all directions at the emission wavelengths.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/ereefs/issues/16<p>

**Comment by roswri** [comment]
Term created:
S041177 - model prediction of fluorescence

**Comment by roswri** [comment]
Term published to NVS:
https://vocab.nerc.ac.uk/collection/S04/current/S041177/
