### ISSUE TITLE
NTR: Request for S04 altimeter

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S04#16]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>altimeter <p><b>Definition</b><p> A device that measures its distance or altitude above a fixed point or surface, such as the seabed or sea level.<p><H2> Optional </H2><p>

**Comment by danibodc** [comment]
This term has been loaded to S04 and will be live on the NVS from tomorrow morning:

S041180	altimeter

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/S04/current/S041180/
