### ISSUE TITLE
NTR: Request for S04 aerial survey

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S04#17]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>aerial survey <p><b>Definition</b><p> The measurement was derived from observations made from the altitude of an aircraft.<p><H2> Optional </H2><p><b>Sources/references</b><p> http://vocab.nerc.ac.uk/collection/P01/current/SAMPARAC/<p>

**Comment by gwemon** [comment]
Terms is now live on the NVS: http://vocab.nerc.ac.uk/collection/S04/current/S041181/
