### ISSUE TITLE
NTR: Request for S04 aerial photography, GIS analysis

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S04#18]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>aerial photography, GIS analysis <p><b>Definition</b><p> The value for the observation was obtained from Geographic Information System (GIS) analysis of aerial images.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/P01/issues/190<p>

**Comment by gwemon** [comment]
The term is live on the NVS: http://vocab.nerc.ac.uk/collection/S04/current/S041182/
