### ISSUE TITLE
NTR: Request for S04 visual estimation of target taxon dominance (100%, >30%, <30%)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S04#19]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>visual estimation of target taxon dominance (100%, >30%, <30%) <p><b>Definition</b><p> The result was obtained using a visual estimate of the percent coverage of a targeted taxon into 3 broad categories: 100%, >30% and <30%  <p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/P01/issues/190<p>

**Comment by gwemon** [comment]
The term is live on the NVS: http://vocab.nerc.ac.uk/collection/S04/current/S041183/
