### ISSUE TITLE
NTR: Request for S04 Smartfin internal temperature sensor (BODCNVS-878)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S04#2]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Smartfin internal temperature sensor <p><b>Definition</b><p> The temperature sensor on the motherboard, in the centre of the Smartfin.<p><H2> Optional </H2><p><b>ORCID</b><p> roswri<p>

**Comment by gwemon** [comment]
@roswri I wanted to include a reference to the description of the Smartfin platform but we don't seem to have a record for it in B76. Should we not be creating one? I found a record for the [Smartfin temperature sensor in L22](http://vocab.nerc.ac.uk/collection/L22/current/TOOL1638/) but this is quite narrowly defined. Is it intended to be specific to the external sensor? If so, do you intend to create another L22 record for the internal sensor?
