### ISSUE TITLE
NTR: Request for S04 Smartfin external temperature sensor (BODCNVS-878)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S04#3]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Smartfin external temperature sensor <p><b>Definition</b><p> The temperature sensor on the tip of the Smartfin. This sensor is more accurate and has a quicker response time than the internal sensor.<p><H2> Optional </H2><p><b>ORCID</b><p> roswri<p>

**Comment by gwemon** [comment]
see https://github.com/nvs-vocabs/S04/issues/2#issuecomment-798960356
