### ISSUE TITLE
NTR: Request for S04 identification and counting by manual image analysis

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S04#5]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>identification and counting by manual image analysis <p><b>Definition</b><p> Identification and quantification of biological entities or other small objects by manual analysis of an image.<p><H2> Optional </H2><p>

**Comment by gwemon** [comment]
Thanks @roswri. Is it correct to restrict this to biological entities and "small objects"? I guess this methology could be applied to any kind of objects identified and counted via manual image analysis so we would be best making the definition less specific.
How about:
"Identification and quantification of any kind of objects using image analysis performed by a human being."?

**Comment by roswri** [comment]
Hi @gwemon,
It feels wrong to refer to a species as an object, so I have revised slightly to:
"Identification and quantification a species or object of any kind using image analysis performed by a human being."
I think that covers all the bases

**Comment by gwemon** [comment]
Hi @roswri  I see a "species" as a biological object and not all biological objects are identified to the species level hence why I think that "species" is too restrcitive. But I see why you may not be comfortable with the definition as suggested so how about:  "Identification and quantification of any kind of biological and non-biological objects using image analysis performed by a human being."?

**Comment by gwemon** [comment]
@roswri  I start doubting my use of the word "object" here. I have checked its usage in relation to biological "things" however I haven't found anything conclusive. I could be the only person in the world using it which is not what we want. Hence lets' change this to: "Identification and quantification of any kind of feature, object, biological organism, or part thereof using image analysis performed by a human being."

**Comment by roswri** [comment]
Thanks @gwemon,

I've made the S04 term S041171 - identification and counting by manual image analysis 
with the definition: 'Identification and quantification of any kind of feature, object, biological organism, or part thereof using image analysis performed by a human being.'
