### ISSUE TITLE
NTR: Request for S04 gas chromatography-isotope ratio mass spectrometry with purge trap system

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S04#6]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>gas chromatography-isotope ratio mass spectrometry<p><b>Definition</b><p> A Gas Chromotograph (GC) coupled with a Isotope Ratio Mass Spectrometer (IRMS).<p><H2> Optional </H2><p><b>Sources/references</b><p> https://www.frontiersin.org/articles/10.3389/fmars.2021.611937/fullhttps://github.com/nvs-vocabs/P01/issues/98<p> <b>Mapping to other terminologies </b><p> http://purl.obolibrary.org/obo/CHMO_0000508<p>

**Comment by gwemon** [comment]
S041172	gas chromatography-isotope ratio mass spectrometry created and queued for publication on the NVS

**Comment by gwemon** [comment]
http://vocab.nerc.ac.uk/collection/S04/current/S041172/ (information about purging and trapping included in the pre-analysis sample preparation component of the P01 code: https://github.com/nvs-vocabs/S03/issues/2)
