### ISSUE TITLE
NTR: Request for S04 acidimetry

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S04#8]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>acidimetry <p><b>Definition</b><p> Use of an acid-base titration assay to determine the concentration of an alkaline substance using standard acid.<p><H2> Optional </H2><p><b>Sources/references</b><p> BODCNVS-1088<p>

**Comment by danibodc** [comment]
This term has now been loaded and will be live on the NVS from 0730 UTC tomorrow morning at:
https://vocab.nerc.ac.uk/collection/S04/current/S041175/
