### ISSUE TITLE
NTR: Request for S04 model prediction of Moderate Resolution Imaging Spectroradiometer (MODIS) output

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S04#9]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>model prediction of Moderate Resolution Imaging Spectroradiometer (MODIS) output <p><b>Definition</b><p> The value was obtained using a numerical model to simulate the output of the Moderate Resolution Imaging Spectroradiometer (MODIS), a 36-band satellite-mounted radiometer measuring from 0.4 um to 14.4 um and at varying spatial resolutions (2 bands at 250 m, 5 bands at 500 m and 29 bands at 1 km).<p><H2> Optional </H2><p><b>Sources/references</b><p> https://modis.gsfc.nasa.gov/about/<p>

**Comment by danibodc** [comment]
This term is now live on the NVS:
http://vocab.nerc.ac.uk/collection/S04/current/S041176/
